[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Medium"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key4"
mods = "Control"

[terminal]

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "tmux"

[window]
opacity = 0.9
decorations = "Full"

[keyboard]
